.PHONY: all run

all: main.exe

CC := g++
CFLAGS_DEBUG := -Og -g3 -ggdb -D_FORIFY_SOURCES=3 -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_EJUDGE_CLIENT_SIDE

Objects/%.o : %.c
	$(CC) $(CFLAGS) $< -c -o $@

SOURCES := Objects/main.o Objects/StackFunc.o Objects/Stackdebug.o Objects/hash.o

main.exe: $(SOURCES)
	$(CC) $(SOURCES) -o main.exe

run: main.exe
	main.exe

clean:
	rm *.o
	rm *.exe

